# Generated by Django 5.1 on 2026-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media_file",
            field=models.FileField(
                blank=True, default="", upload_to="chat_media/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="media_filename",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="message",
            name="media_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
