# Generated by Django 5.1 on 2026-04-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_media_file_message_media_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_companies",
            field=models.ManyToManyField(
                blank=True, related_name="agents", to="core.company"
            ),
        ),
    ]
