# Generated by Django 5.1 on 2026-04-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_allowed_companies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="allowed_services",
        ),
        migrations.AddField(
            model_name="company",
            name="ticket_created_message",
            field=models.TextField(
                blank=True, default="", help_text="Custom message after ticket creation"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="welcome_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom greeting when user selects this company",
            ),
        ),
        migrations.AlterField(
            model_name="botconfig",
            name="priority",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
